kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: locust-master
  labels:
    component: "master"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: locust
        component: "master"
    spec:
      containers:
        - name: locust
          image: gcr.io/${LTK_DRIVER_PROJECT_ID}/ltk-master:latest
          env:
            - name: LOCUST_MODE
              value: master
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
          livenessProbe:
            periodSeconds: 30
            httpGet:
              path: /
              port: 8089
          readinessProbe:
            periodSeconds: 30
            httpGet:
              path: /
              port: 8089
