kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: locust-worker
  labels:
    app: locust-worker
    component: worker
spec:
  serviceName: locust-worker
  replicas: ${LTK_NUM_LOCUST_WORKERS}
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - locust-worker
                - locust
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: locust
          image: gcr.io/${LTK_DRIVER_PROJECT_ID}/ltk-worker:latest
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER_HOST
              value: locust-master
            - name: LOCUST_MASTER_PORT
              value: "5557"
            - name: BLOCK_SIZE
              value: "${blockSize}"
            - name: PROJECT_ID
              value: "${LTK_TARGET_PROJECT_ID}"
            - name: REGION
              value: "${LTK_TARGET_REGION}"
            - name: REGISTRY_ID
              value: "${LTK_TARGET_REGISTRY_ID}"

