steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/angular-nginx-container', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/$PROJECT_ID/angular-nginx-container']
images: ['us.gcr.io/$PROJECT_ID/angular-nginx-container']