main:
  params: [args]
  steps:
    - init:
        assign:
          - headers: ${args.headers}
          - body: ${args.body}
    - log1:
        call: sys.log
        args:
            text: Workflows received request
            severity: INFO
    - log2:
        call: sys.log
        args:
            text: ${args}
            severity: INFO
    - pubSubMessageStep:
        call: sys.log
        args:
            text: ${"Decoded Pub/Sub message data is " + text.decode(base64.decode(args.body.message.data))}
            severity: INFO

