runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/push-handlers/.*
  script: main.app
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: .*
  script: main.app
