apiVersion: v1
kind: ConfigMap
metadata:
  name: device-config
data:
  PROJECT_ID: PROJECT
  REGISTRY_ID: gadgets
  BRIDGE_DEVICE_ID: bridge
  CLOUD_REGION: us-central1 
  JWT_EXPIRATION_MINUTES: "600"
  CONFIG_REFRESH_MINUTES: "500" 