apiVersion: apps/v1
kind: Deployment
metadata:
  name: "micronaut-jvm-metrics"
spec:
  selector:
    matchLabels:
      app: "micronaut-jvm-metrics"
  template:
    metadata:
      labels:
        app: "micronaut-jvm-metrics"
    spec:
      serviceAccount: micronaut-application
      containers:
        - name: "micronaut-jvm-metrics"
          image: "gcr.io/[PROJECT_ID]/micronaut-jvm-metrics"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: "micronaut-jvm-metrics-svc"
spec:
  selector:
    app: "micronaut-jvm-metrics"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
