apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: metric-puller
  name: metric-puller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: metric-puller
      name: metric-puller
    spec:
      containers:
        - name: metric-puller
          image: "gcr.io/cloud-solutions-images/metric-puller:0.0.1"
          imagePullPolicy: Always
          args: ["--project", "ptone-serverless", "--subscription", "metric-pull"]
