apiVersion: v1
kind: Service
metadata:
  labels:
    app: metric-puller
  name: metric-puller
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: metric-puller
