#!/bin/bash

### BEGIN INIT INFO
# Provides:        coap-proxy
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start coap-proxy
### END INIT INFO

# simple script to start/stop the proxy

LOGDIR="/var/log/coap-proxy"
BINDIR="/usr/local/coap-proxy"
DTLS_CONF="/etc/coap-proxy.conf"

cd $BINDIR
RUNAS="coap-proxy"

if [ ! -d $LOGDIR ]; then
  echo "$LOGDIR does not exist - using /tmp/proxy.log"
  LOGDIR="/tmp"
fi

LOGFILE="$LOGDIR/proxy.log"

start() {
  echo "Starting COAP proxy.."
  if pgrep -f "java -jar coap-iot-core-1.0-SNAPSHOT.jar"; then
    echo "Looks like you have one running already. Try stopping it."
    exit 1
  fi
  runuser -m $RUNAS -c "source $DTLS_CONF && java -jar coap-iot-core-1.0-SNAPSHOT.jar >> $LOGFILE 2>&1 &"
  # Make sure it started
  sleep 1
  if pgrep -f "java -jar coap-iot-core-1.0-SNAPSHOT.jar"; then
    echo "Proxy started."
  else
     echo "Proxy didn't start. Check the logs in $LOGDIR"
  fi
}

stop() {
 echo "Stopping proxy.."
 PID=`pgrep -f "java -jar coap-iot-core-1.0-SNAPSHOT.jar"`
 kill $PID
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
