apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-psweb
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: service-nfs.default.svc.cluster.local
    path: "/psdata"
  claimRef:
     namespace: default
     name: pvc-psweb
