apiVersion: v1
kind: Service
metadata:
  name: service-psweb
  annotations:
    cloud.google.com/backend-config: '{"default": "bc-psweb"}'
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
  selector:
    app: server-psweb
