apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-psweb
  labels:
    type: local
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
