apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress-resource
spec:
  backend:
    serviceName: hello-app
    servicePort: 8080
