{
 "title": "Device Detail View",
 "time": { "from": "now-4h", "to": "now+5m" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "device_id",
    "label": "Device ID",
    "query": "label_values(device_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Luminance Predictions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "predict_linear(room_luminance{instance=\"$device_id\"}[15m], 300   )\n",
     "legendFormat": "Predicted"
    },
    {
     "expr": "room_luminance{instance=\"$device_id\"}",
     "legendFormat": "Actual"
    }
   ]
  },
  { "title": "Temp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Temp Celcius" }
   ],
   "targets": [
    {
     "expr": "avg_over_time( room_external_temp{instance=\"$device_id\"}[15m])",
     "legendFormat": "15min avg"
    },
    {
     "expr": "room_external_temp{instance=\"$device_id\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "room_external_temp{instance=\"$device_id\"}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Message Data Rate",
   "type": "graph",
   "description": "Messages per minute over trailing 10m",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "msgs/min" }
   ],
   "targets": [
    {
     "expr": "rate(device_msgs_total{instance=\"$device_id\"}[10m]) * 60"
    }
   ]
  }
 ]
}