{
 "title": "Region Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(device_info, region)"
   },
   {
    "name": "firmware",
    "label": "Firmware",
    "query": "label_values(device_info, firmware)"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 0 }, "content": "# $region" },
  {
   "title": "Crashing Devices",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "topk(10, changes(device_boot_time[1h]) * on (instance) group_left(region, firmware) device_info{region=\"$region\", firmware=~\"$firmware\"})",
     "legendFormat": "{{ instance }} [{{ firmware }}]"
    }
   ]
  },
  {
   "title": "Longest running devices",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "topk(5, time() - device_boot_time* on (instance) group_left(region, firmware)  device_info{region=\"$region\", firmware=~\"$firmware\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Current Devices",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(device_boot_time* on (instance) group_left(region, firmware)  device_info{region=\"$region\", firmware=~\"$firmware\"}) "
    }
   ]
  },
  {
   "title": "Hottest Devices",
   "type": "graph",
   "description": "Top 3 devices by temperature in region",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, room_external_temp * on (instance) group_left(region, firmware)  device_info{region=\"$region\", firmware=~\"$firmware\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Devices with lid open",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (instance, firmware) (lid_open_status * on (instance) group_left(region, firmware)  device_info{region=\"$region\", firmware=~\"$firmware\"}) "
    }
   ]
  },
  {
   "title": "Temperature Distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "room_external_temp * on (instance) group_left(region, firmware)  device_info{region=\"$region\", firmware=~\"$firmware\"}"
    }
   ]
  },
  {
   "title": "Issue Notes (from Google Sheets)",
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 15 },
   "content": "<style>\nbody {\n    margin: 0;\n}\n.parent {\n    display: flex;\n    flex-direction: column;\n    min-height: 100vh;\n}\n.parent .banner {\n    background: #f00;\n    width: 100%;\n    height: 30px;\n}\n.parent iframe {\n    background: #000;\n    border: none;\n    flex-grow: 1;\n}\n</style>\n\n\n<div class=\"parent\">\n<iframe src=\"https://docs.google.com/spreadsheets/d/1FvwKEqVbnY1k3ZfQ3SJNLr-CAb3U_3bIOIFe_XE2wGY/htmlembed?single=true&gid=0&widget=false&chrome=false\"></iframe>\n</div>"
  }
 ]
}