apiVersion: "v1"
kind: "Service"
metadata:
  name: "mqtt-bridge"
  namespace: "default"
  labels:
    app: "iot-core-bridge"
spec:
  ports:
  - protocol: "TCP"
    port: 1883
    targetPort: 1883
  selector:
    app: "iot-core-bridge"
  type: "LoadBalancer"
  loadBalancerIP: ""