apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: karma
  name: karma
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: karma
      name: karma
    spec:
      containers:
        - name: karma
          image: "lmierzwa/karma:latest"
          imagePullPolicy: Always
          env:
          - name: ALERTMANAGER_URI
            value: "http://iotmonitor-prometheus-alertmanager"
---
apiVersion: v1
kind: Service
metadata:
  name: karma
  labels:
    app: karma
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: karma