apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: simulator
  name: simulator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simulator
      name: simulator
    spec:
      containers:
        - name: simulator
          image: "gcr.io/cloud-solutions-images/simulator:0.0.1"
          imagePullPolicy: Always
          env:
          - name: DEVICE_COUNT
            value: "500"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simulator
  name: simulator
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: simulator