apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-deployment
spec:
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      volumes:
      - name: output
        hostPath:
          path: /tmp
      containers:
      - name: yolo
        image: us-central1-docker.pkg.dev/#PROJECT_ID#/edge-deployment-demo/edge-ai:#BUILD#
        env:
        - name: SOURCE
          value: "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"
        - name: OUTPUT
          value: "/app/output/"          
        volumeMounts:
        - name: output
          mountPath: /app/output