apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gke-viai
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-standard
  fstype: ext4
  # replication-type: none
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
spec:
  storageClassName: gke-viai
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
