apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: event-display
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/knative-releases/github.com/knative/eventing-contrib/cmd/event_display@sha256:1d6ddc00ab3e43634cd16b342f9663f9739ba09bc037d5dea175dc425a1bb955
---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
  namespace: default
spec:
  consumerGroup: knative-group
  bootstrapServers:  CONFLUENT-SERVER
  topics: cloudevents
  net:
    sasl:
      enable: true
      user:
        secretKeyRef:
          name: kafka-secret
          key: user
      password:
        secretKeyRef:
          name: kafka-secret
          key: password
    tls:
      enable: true
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-display
