apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: gcr.io/ptone-kf/auth-client
  googleCloudBuild:
    timeout: 600s
deploy:
  kubectl:
    flags:
      apply:
        - --namespace=id-namespace
    manifests:
      - k8s-*
