apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: currency-sink-goog
spec:
  template:
    spec:
      containers:
      - image: gcr.io/yokicloud/currency-sink
        imagePullPolicy: Always