#!/bin/sh

STATE_CHANGE_ALLOW=0
STATE_CHANGE_DISALLOW=1
STATE_CHANGE_RETRY=21

# Change this conditional to an appropriate check
# to ensure server communication will succeed.
if [ -e /data/mender/preauth_true ]; then
    exit $STATE_CHANGE_ALLOW
else
    exit $STATE_CHANGE_RETRY
fi
