apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependency-track

configMapGenerator:
- name: dt-frontend-application-properties
  literals:
    - API_BASE_URL=https://$DT_DOMAIN_API

images:
  - name: dependency-track-frontend
    newName: $GCP_REGISTRY/frontend
    newTag: 1.2.0

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
