apiVersion: v1
kind: Service
metadata:
  name: service-nfs
spec:
  type: NodePort
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: server-nfs
