apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-psweb
spec:
  rules:
  - host: "ps.example.com"
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: service-psweb
            port:
              number: 80
