on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron:  '0 7 * * *'
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 8
      - run: npm install
      - run: npm test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 8
      - run: npm install
      - run: npm run lint
